### ISSUE TITLE
Make design https://127.0.0.1:8080

### ISSUE THREAD

**Issue by arufanov** [a5lab/axion#191]
Make design https://tabr.a5lab.com/

**Comment by arufanov** [comment]
@OksanaSidorova 
* here is site https://axion.a5lab.com/ to design.

**Comment by OksanaSidorova** [comment]
Hi @arufanov design for home page https://www.figma.com/proto/3pZxhWPCV0A8hYvuxqckJC/Technical-and-business-radar_2?page-id=0%3A1&node-id=113%3A279&viewport=-638%2C-1163%2C0.21&scaling=scale-down-width

**Comment by arufanov** [comment]
@OksanaSidorova 
* looks super! 
* do you understand dynamic features: either create radar buttons or pictures of radar. 
* do you understand that picture of radar is dynamic (create by jscript and I am not able to style it). 
* take a look at https://axion.a5lab.com/settings/tenants and https://github.com/bezkoder/thymeleaf-pagination-sorting-example. We can use the same approach to filter, sorting and paging. I hope that this info help
* Can you develop styles based on pages axion/src/main/resources/static? This statical pages use exactly the same styles.

**Comment by arufanov** [comment]
@OksanaSidorova 
* here is file to add style https://github.com/a5lab/axion/tree/main/src/main/resources/static/css filename: application.css
* here is folder for images https://github.com/a5lab/axion/tree/main/src/main/resources/static/images
* here is folder for jscript https://github.com/a5lab/axion/tree/main/src/main/resources/static/js. I suppose that you will not need it.
* there are 2 files: filter & index at https://github.com/a5lab/axion/tree/main/src/main/resources/static. This files are copy for index/home page and one page with filter. You can test styles based on this files.  We use thymleaf as template engine and home files localted at https://github.com/a5lab/axion/tree/main/src/main/resources/templates/home + layout at https://github.com/a5lab/axion/tree/main/src/main/resources/templates/layouts. 

Summary: let start to work at followay:
*  I will change markup at thymleaf files & static files from https://github.com/a5lab/axion/tree/main/src/main/resources/static based on you requirements.
* You will changes styles and images files at https://github.com/a5lab/axion/tree/main/src/main/resources/static/css and https://github.com/a5lab/axion/tree/main/src/main/resources/static/images. 
*We will use pr to discuss the result. 

Is it ok?

**Comment by OksanaSidorova** [comment]
Hi @arufanov ok, thank you!

**Comment by OksanaSidorova** [comment]
@arufanov 

pages for axion here
https://www.figma.com/file/3pZxhWPCV0A8hYvuxqckJC/Technical-and-business-radar_2?node-id=0%3A1

 - Page after radar created https://www.figma.com/file/3pZxhWPCV0A8hYvuxqckJC/Technical-and-business-radar_2?node-id=156%3A3&t=8WNCbcodz6dTtVcN-1
 - settings/technology_blips page https://www.figma.com/file/3pZxhWPCV0A8hYvuxqckJC/Technical-and-business-radar_2?node-id=157%3A11568&t=8WNCbcodz6dTtVcN-1
 - accounts/notifications page https://www.figma.com/file/3pZxhWPCV0A8hYvuxqckJC/Technical-and-business-radar_2?node-id=157%3A16702&t=8WNCbcodz6dTtVcN-1

**Comment by arufanov** [comment]
@OksanaSidorova 
super! 

about https://www.figma.com/file/3pZxhWPCV0A8hYvuxqckJC/Technical-and-business-radar_2?t=2y3rDttKWspNFf2K-0
* lest use this version 
<img width="266" alt="Screenshot 2023-02-26 at 22 59 56" src="https://user-images.githubusercontent.com/135741/221434012-e15315bb-2709-4ade-a1cd-358f5e1545a8.png">
* block "what is purpose" move below tables, above "how do we maintian"
* lets use single logo for herader and footer.


about https://www.figma.com/file/3pZxhWPCV0A8hYvuxqckJC/Technical-and-business-radar_2?node-id=157%3A11568.
* filter is clickable, it hide/show filter
* let's join show, edit, delete at single columnt actions. There is change to have a new actions such as clone and etc.
* I don't like footer. It consume a lot of space. footer and header have different log.  We can left only copyright. Or something like this  
<img width="1387" alt="Screenshot 2023-02-26 at 23 07 16" src="https://user-images.githubusercontent.com/135741/221434400-cc0c4498-c2ec-48b4-84d0-88ace3666298.png">: github on the left & copyright on the right. I like this idea. Taken from https://rasa.com/.


super, 
* footer. as above
* you have missed box on the bottom. Should we leave it? 
<img width="731" alt="Screenshot 2023-02-26 at 23 10 25" src="https://user-images.githubusercontent.com/135741/221434563-7ba35926-4de7-434a-a6aa-0933398c6f41.png">

**Comment by OksanaSidorova** [comment]
Hi @arufanov 

I fixed here https://www.figma.com/file/3pZxhWPCV0A8hYvuxqckJC/Technical-and-business-radar_2?node-id=174%3A9592&t=XPZYi54QXEgDTVaz-1

About logo:
 -  what titles (words) should be in the logo?
 -  will this logo be used on both sites?

**Comment by arufanov** [comment]
@OksanaSidorova 
* thanks! 
* "what titles (words) should be in the logo?" axion (or Axion, or AXION).
* "will this logo be used on both sites?" for now -yes.

**Comment by OksanaSidorova** [comment]
@arufanov I've change the logo on axion mock-ups

**Comment by arufanov** [comment]
@OksanaSidorova 
* logo is super!  lets changes log at axion & a5lab.

**Comment by arufanov** [comment]
@OksanaSidorova 
* I will close this issue. We have already done design. Now we are working on markup. Thanks!
