### ISSUE TITLE
Create docs for tabr

### ISSUE THREAD

**Issue by arufanov** [a5lab/axion#249]
Create docs for tabr. I have created structure for https://docs.a5lab.com/tabr/0.1.0/index.html. Don't change it. Could you create a doc for each page. Own issue(?), branch, pr  for each page please.

**Comment by cherokee94** [comment]
@arufanov got it – for every file (adoc) a new issue/branch/pr

**Comment by cherokee94** [comment]
── ROOT
│   ├── nav.adoc
│   └── pages
│       └── index.adoc
├── best_practices
│   ├── nav.adoc
│   └── pages
│       ├── administration_best_practices.adoc
│       ├── infrastructure_best_practices.adoc
│       └── overview.adoc
├── installation
│   ├── nav.adoc
│   └── pages
│       ├── application_configuration.adoc
│       ├── database_configuration.adoc
│       ├── installation_from_binaries.adoc
│       ├── installation_from_sources.adoc
│       ├── installation_methods.adoc
│       ├── installation_prerequisites.adoc
│       ├── overview.adoc
│       ├── run_as_service.adoc
│       ├── runtime_env_configuration.adoc
│       └── system_requirements.adoc – https://github.com/a5lab/tabr/issues/252
├── release_notes
│   ├── nav.adoc
│   └── pages
│       ├── 0.9.0.adoc
│       ├── 1.0.0.adoc
│       └── overview.adoc
└── usage
    ├── nav.adoc
    └── pages
        ├── concepts.adoc
        ├── overview.adoc
        └── user_interface_overview.adoc

**Comment by arufanov** [comment]
@cherokee94 
* can we close this root issue? I suppose that process is working and we can close this issue. Can we?  If no then reopen issue.
