### ISSUE TITLE
Docs - application configuration

### ISSUE THREAD

**Issue by cherokee94** [a5lab/axion#268]
Supported 2 way to configure app:
.By command line parameres
.By application yml

== The first one
Based on:
ExecStart=java -jar {{ app__current_path }}/target/axion-0.1.0-SNAPSHOT.jar --application.keys.google_analytics={{ app__google_analytics }}

== The second one
Put aplicatoin.yml at axion and edit application.yml

**Comment by cherokee94** [comment]
@arufanov about the second one – where do we put the yml? ...
or do you mean the application.yml that comes with the source files?

**Comment by arufanov** [comment]
> @arufanov about the second one – where do we put the yml? ... or do you mean the application.yml that comes with the source files?

@cherokee94 
* I have never check it, but @yurichervoniy said: 
```
axion-....jar
application.yml
```

if application yml located near axion -....jar then axion will read information from application.yml. Is it answer?

**Comment by arufanov** [comment]
@cherokee94 we will check @A9afon this statement later.
