### ISSUE TITLE
Fix error during startup "found character '@' that cannot start any token. (Do not use @ for indentation)"

### ISSUE THREAD

**Issue by arufanov** [a5lab/axion#317]
**Describe the bug**

```
23:48:31.257 [restartedMain] ERROR org.springframework.boot.SpringApplication - Application run failed
org.yaml.snakeyaml.scanner.ScannerException: while scanning for the next token
found character '@' that cannot start any token. (Do not use @ for indentation)
 in 'reader', line 29, column 13:
        active: @spring.profiles.active@
                ^

	at org.yaml.snakeyaml.scanner.ScannerImpl.fetchMoreTokens(ScannerImpl.java:470)
	at org.yaml.snakeyaml.scanner.ScannerImpl.checkToken(ScannerImpl.java:263)


```

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by A9afon** [comment]
https://github.com/spring-projects/spring-boot/issues/8438 @arufanov fyi

**Comment by arufanov** [comment]
@A9afon 
* thanks. Fixed by direct commit to main https://github.com/a5lab/axion/commit/245bac4a01bc3b4e33f4169c368fb3948fe9a8c8 . It is invalid, my fault.
