### ISSUE TITLE
Filter doesnt work settings/rings

### ISSUE THREAD

**Issue by A9afon** [a5lab/axion#334]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by arufanov** [comment]
@A9afon 
* could you fix similar to #345

**Comment by arufanov** [comment]
@A9afon 
* fixed, reopen in case fixes is not ok
