### ISSUE TITLE
Button "Delete" radar doesn't work and throws an error 500

### ISSUE THREAD

**Issue by A9afon** [a5lab/axion#360]
500 error is raised when removing a radar if it was the only one

**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by arufanov** [comment]
@A9afon 
* " it was the only one" this is not true. Real problem is referenced data.
