### ISSUE TITLE
Duplication of instructions

### ISSUE THREAD

**Issue by A9afon** [a5lab/axion#411]
Go to "https://axion.a5lab.com/settings/rings/create".
Click on "Add ring".
See duplication of instructions such as "не должно быть пустым", "размер должен находиться в диапазоне от 1 до 8" , "should be uppercase", "размер должен находиться в диапазоне от 1 до 512".

**Comment by arufanov** [comment]
@A9afon 
* fixed by https://github.com/a5lab/axion/pull/413. Reopen if you are not agree.
