### ISSUE TITLE
Fix warning from the log

### ISSUE THREAD

**Issue by arufanov** [a5lab/axion#512]
Fix warning from the log
* 2023-04-21T23:58:46.281+03:00  WARN 23868 --- [  restartedMain] io.undertow.websockets.jsr               : UT026010: Buffer pool was not set on WebSocketDeploymentInfo, the default pool will be used
* 2023-04-21T23:58:47.933+03:00  WARN 23868 --- [  restartedMain] org.hibernate.orm.deprecation            : HHH90000021: Encountered deprecated setting [javax.persistence.sharedCache.mode], use [jakarta.persistence.sharedCache.mode] instead

**Comment by A9afon** [comment]
@arufanov 
Possible solutions:

1. Warning: https://stackoverflow.com/questions/60705285/websocketdeploymentinfo-the-default-worker-will-be-used
We can add this pattern. Will this solve the problem?:
```
@Component
public class CustomizationBean implements WebServerFactoryCustomizer<UndertowServletWebServerFactory> {
 
    @Override
    public void customize(UndertowServletWebServerFactory factory) {
        factory.addDeploymentInfoCustomizers(deploymentInfo -> {
            WebSocketDeploymentInfo webSocketDeploymentInfo = new WebSocketDeploymentInfo();
            webSocketDeploymentInfo.setBuffers(new DefaultByteBufferPool(false, 1024));
            deploymentInfo.addServletContextAttribute("io.undertow.websockets.jsr.WebSocketDeploymentInfo", webSocketDeploymentInfo);
        });
    }
}
```

2. Warning: https://github.com/spring-projects/spring-data-jpa/issues/2717#issuecomment-1336159936
There is a solution for this problem. Need to explicitly set one of:
```
 /**
     * All entities and entity-related state and data are cached.
     */
    ALL, 

    /**
     * Caching is disabled for the persistence unit.
     */
    NONE, 

    /**
     * Caching is enabled for all entities for <code>Cacheable(true)</code>
     * is specified.  All other entities are not cached.
     */
    ENABLE_SELECTIVE, 

    /**
     * Caching is enabled for all entities except those for which
     * <code>Cacheable(false)</code> is specified.  Entities for which
     * <code>Cacheable(false)</code> is specified are not cached.
     */
    DISABLE_SELECTIVE, 

    /**
     * 
     * Caching behavior is undefined: provider-specific defaults may apply.
     */
    UNSPECIFIED
```
Will this fix the problem?

**Comment by arufanov** [comment]
@A9afon 
* not obvious task a) https://springhow.com/spring-boot-undertow/ change undertow to tomcat. b) use exclusion according to https://stackoverflow.com/questions/60705285/websocketdeploymentinfo-the-default-worker-will-be-used  "<exclusion><artifactId>undertow-websockets-jsr</artifactId><groupId>io.undertow</groupId></exclusion>" See https://springhow.com/spring-boot-undertow/ as example of exclustion
* "Will this fix the problem?" Lets try. Could you test and provide pr?
