### ISSUE TITLE
Set linear history

### ISSUE THREAD

**Issue by A9afon** [a5lab/axion#533]
@arufanov 
 > **Tutorial to set linear history;**

Repository -> Settings -> Branches -> Add branches protection rule or edit rule -> Require linear history - true.

![Release](https://user-images.githubusercontent.com/121198723/236636809-3e48ded1-cbad-471e-a18c-db173180dd2f.png)

> **Result**

![Release](https://user-images.githubusercontent.com/121198723/236638740-36d50c1a-ba91-465e-b11c-db78cb5e6074.png)

**Comment by arufanov** [comment]
@A9afon 
* thanks! Checked "revent merge commits from being pushed to matching br"
