### ISSUE TITLE
Configure GPG signature

### ISSUE THREAD

**Issue by arufanov** [a5lab/axion#554]
* How to configure GPG signature in orde to avoid "committed by GitHub <noreply@github.com>      Unverified GPG signature"
* Disable commit without GPG signature
* https://docs.github.com/en/authentication/managing-commit-signature-verification/generating-a-new-gpg-key
* https://binx.io/2021/12/06/why-you-should-start-signing-your-git-commits-today/

**Comment by A9afon** [comment]
@arufanov  fyi

[https://gist.github.com/aortbals/2aeb557bf127dd7ae88ea63da93479fc](url)

Squash and merge rewrites the author of the commit to itself
