### ISSUE TITLE
Implementation of the project in axion

### ISSUE THREAD

**Issue by A9afon** [a5lab/axion#608]
SP: 1
Sprint: 3.07.23

1. What is the current project in terms of github?
2. How are milestone related to the roadmap?
3. What is workflow?
4. How to create team vs personal boards?
     
>   - How to create a scrum board?  
>   - How to view team velocity & burn down chart?

5. The board must be linked to the repo (all issues) and only see open ones.
6. All tasks must be added from the repository.
 > - How to filter by status in the project (only new tasks)?
 > - Where are the closed tasks?
 > - Where is the pull request on the board?
 > - Where on the board PR?
 > - Where are the closed tasks?
7. Maybe 2 boards are needed for issue & PR?

**Comment by A9afon** [comment]
@arufanov 

1. A project is a responsive spreadsheet that integrates with GitHub issues and pull requests to help you efficiently plan and get your work done. You can design and create custom fields to represent team-specific metadata.
  2. Use a milestone to track progress across issue groups or pull requests in a repository.

     - When you create a milestone, you can associate it with issues and pull requests.

      - A user-provided description of the milestone, which may include general information about the project, as well as data about teams and scheduled due dates;
      - Milestone completion date;
      - Milestone completion percentage;
      - The number of open and closed issues and pull requests associated with the milestone.
      - List of open and closed issues and pull requests associated with the milestone.
   3. Workflow is designed to automate pull requests. In the example workflows, when the pull request is marked as "ready for review", a new task is added to the project with a "Status" field set to "Todo", and the current date is added to a custom "Date posted" field.
   4. [Go to](https://github.com/orgs/a5lab/projects/2) and add "New view" for create new board. For team boards, you need to set the "is: issue" filter. for a personal board, you must additionally specify "assigners:person" in the filter.
           - [Go to](https://github.com/orgs/a5lab/projects/2/insights?layout=line) and configure the filter with the last-updated:7days command you will see all the tasks of each person and what status they have been in for the last 7 days.
      
5. In a project, an issue is automatically sent to the board using workflow. Also several repositories can be associated with one project to see common tasks on one board.
6. "Add item" is the creation of an additional task state status. I propose to create separate statuses for each type of task state. For example: approval requirement or review requirements - Review, tasks in draft status - Draft, merged branches with the main branch - Merged. This will automatically sort all the tasks on the board. Closed tasks will be in the status - Done, and merged branches - Merged

**Comment by arufanov** [comment]
@A9afon 
lets discuss and close. Thanks!

**Comment by A9afon** [comment]
@arufanov 

> Is it possible to automate filtering depending on which user opens the project?
   
   - There is no such variation of the workflow in the project.
>  Is it possible to write a script for a workflow project myself?

  - There is no such possibility in the project.
> Filter tasks in the project "last added in 15 days"
 
  - -updated:<@today-15d shows last tasks added/updated in 15 days
> Is it possible to add auto-add to a project?
  - yes you can. The "auto-add to project" workflow allows you to do this

**Comment by arufanov** [comment]
@A9afon 
* lets do
```
Filter tasks in the project "last added in 15 days"

-updated:<@today-15d shows last tasks added/updated in 15 days
Is it possible to add auto-add to a project?

yes you can. The "auto-add to project" workflow allows you to do this

```

Could you give me url for a) "The "auto-add to project" workflow allows you to do this" b) "Is it possible to write a script for a workflow project myself" how to add scripts. Thansk!

**Comment by arufanov** [comment]
@A9afon 
* thanks! I don't have any questions
