### ISSUE TITLE
Fix inconsistent answers

### ISSUE THREAD

**Issue by A9afon** [a5lab/axion#623]
1. Go to 'http://127.0.0.1:8080/settings/tenants/add';
2. Create some tenant;
3. Go to 'http://127.0.0.1:8080/settings/tenants';
4. Click on button 'delete';
5. See on devTools Network: Http request method 'GET' and StatusCode '302 FOUND';
6. But Test shouldDeleteTenant in TenantCfgIntegrationTests have Http request method 'GET' and StatusCode '200 OK';
7. Find out what is the reason.

**Comment by arufanov** [comment]
This issue have already fixed
