### ISSUE TITLE
Create tests for the possible to change the active radar in ring and segment

### ISSUE THREAD

**Issue by A9afon** [a5lab/axion#700]
SP: 2
Sprint: 17.07.23
 
1.   Add validation:

  - [ ] Ring/Segmnet can't be edited radar field if ring/segment belong active radar
  - [ ] Ring/Segmnet can't be delited radar field if ring/segment belong active radar
  

2. Create test for method:

  - [ ] Update radar field in Ring/Segment 
  - [ ] Delete Ring/Segment

**Comment by arufanov** [comment]
@A9afon 
* create https://github.com/a5lab/axion/issues/704 for implementation
